### ISSUE TITLE
option to remove "Battery additional information rectangel"

### ISSUE THREAD

**Issue by MonsterD1** [slipx06/sunsynk-power-flow-card#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on the lite version the battery part has a rectangle to implement additionl information on W/A etc. there is no configuration available to remove the rectangle if not needed. 

[https://community.home-assistant.io/t/sunsynk-deye-inverter-power-flow-card/562933/234?u=monster_d](url)

### Expected behaviour

the additional information rectangel should be hideble on option. 

### Possible Solutions

option to remove the rectangle

### Mode

Both

### Context / Reason

the look and feel of the view is much better without empty rectangel.

**Comment by slipx06** [comment]
Hi. The card is designed to work with a minimum set of data. This includes battery power, current and volts so that rectangle should not be empty. For now you should set the attributes to none to hide them.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/0349de25-360e-4e3f-833f-c6f3aebbc050)

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/32e8f356-d94b-43d0-8869-6b0514824511)

**Comment by slipx06** [comment]
Busy working on a new layout see #156
