### ISSUE TITLE
suppress duplicative values

### ISSUE THREAD

**Issue by jpettitt** [slipx06/sunsynk-power-flow-card#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As you can see in this screenshot there is a redundant `0W` value for solar and for the hot tub. Due to there only being one entity contributing this value all always be the same at the one next to it.  

<img width="500" alt="image" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/524856/209d4da8-908a-4d7e-8647-72cf5426ee28">

### Expected behaviour

Don't show redundant values

### Possible Solutions

Would it be possible to suppress the redundant value?

### Mode

full

### Context / Reason

Most people won't have multiple solar inverters (or if they have microinverters like I do they have too many to enumerate them all)

**Comment by slipx06** [comment]
Hi. I'm glad that you are finding a use for the card. The original design goal was to emulate the Sunsynk system flow screen and display the corresponding sensor values.  It may not work as intended if you are using your own sensor values but there are some configuration options you can try.  As an example the additional non-essential load is nor meant to be representative of everything connected to the non-essential side. So ordinarily you should not have any redundant values. Many people have multiple loads connected i.e. Heater, Aircon, Oven etc but only have energy monitoring on one or two specific loads.  In your case if you only have one load contributing and connected on the non-essential side, then rather set the additional_loads: 0 and change the icon.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/baba9b4d-447f-4af6-a90f-ee6b85b3beea)

For solar there may be some redundancy if you only have one MPPT but the first values shows additional PV voltage and current.  Total solar will be redundant but the solar export icon is displayed and would seem out of place if removed

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/29eccab6-e585-4da7-b624-dd126e43bd54)

Unfortunately due to the design constraints (SVG elements, layers, positioning) etc modifying the card layout is not a trivial process when it comes to big changes.
