### ISSUE TITLE
Add daily energy for essential loads (additional_loads)

### ISSUE THREAD

**Issue by pipip** [slipx06/sunsynk-power-flow-card#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Essential loads show the current power (essential_load1, essential_load2)

### Expected behaviour

I would like to add the daily energy in kWh (e.g
: day_essential1_energy and day_essential2_energy)

### Mode

lite

### Context / Reason

Everything else in this card shows current power as well as daily energy. Essential is missing the daily energy values.

I would love to see energy usage for heatpump and "rest of house" in the card.

**Comment by slipx06** [comment]
Hi


You can now display extra sensor data for your additional essential loads e.g. daily energy or temperature etc. The following optional entities can be used: essential_load1_extra and essential_load2_extra. This data is not displayed on the full card if show_aux: true due to insufficient space.

https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.8.0
